namespace Constants {

    export class Countries {
        public static getCountries() {
            return [
                { Value : "United States", Text : "United States" },
                { Value : "Afghanistan", Text : "Afghanistan" },
                { Value : "Albania", Text : "Albania" },
                { Value : "Algeria", Text : "Algeria" },
                { Value : "American Samoa", Text : "American Samoa" },
                { Value : "Andorra", Text : "Andorra" },
                { Value : "Angola", Text : "Angola" },
                { Value : "Anguilla", Text : "Anguilla" },
                { Value : "Antarctica", Text : "Antarctica" },
                { Value : "Antigua and Barbuda", Text : "Antigua and Barbuda" },
                { Value : "Argentina", Text : "Argentina" },
                { Value : "Armenia", Text : "Armenia" },
                { Value : "Aruba", Text : "Aruba" },
                { Value : "Australia", Text : "Australia" },
                { Value : "Austria", Text : "Austria" },
                { Value : "Azerbaijan", Text : "Azerbaijan" },
                { Value : "Bahamas", Text : "Bahamas" },
                { Value : "Bahrain", Text : "Bahrain" },
                { Value : "Bangladesh", Text : "Bangladesh" },
                { Value : "Barbados", Text : "Barbados" },
                { Value : "Belarus", Text : "Belarus" },
                { Value : "Belgium", Text : "Belgium" },
                { Value : "Belize", Text : "Belize" },
                { Value : "Benin", Text : "Benin" },
                { Value : "Bermuda", Text : "Bermuda" },
                { Value : "Bhutan", Text : "Bhutan" },
                { Value : "Bolivia", Text : "Bolivia" },
                { Value : "Bosnia and Herzegovina", Text : "Bosnia and Herzegovina" },
                { Value : "Botswana", Text : "Botswana" },
                { Value : "Bouvet Island", Text : "Bouvet Island" },
                { Value : "Brazil", Text : "Brazil" },
                { Value : "British Indian Ocean Territory", Text : "British Indian Ocean Territory" },
                { Value : "Brunei Darussalam", Text : "Brunei Darussalam" },
                { Value : "Bulgaria", Text : "Bulgaria" },
                { Value : "Burkina Faso", Text : "Burkina Faso" },
                { Value : "Burundi", Text : "Burundi" },
                { Value : "Cambodia", Text : "Cambodia" },
                { Value : "Cameroon", Text : "Cameroon" },
                { Value : "Canada", Text : "Canada" },
                { Value : "Cape Verde", Text : "Cape Verde" },
                { Value : "Cayman Islands", Text : "Cayman Islands" },
                { Value : "Central African Republic", Text : "Central African Republic" },
                { Value : "Chad", Text : "Chad" },
                { Value : "Chile", Text : "Chile" },
                { Value : "China", Text : "China" },
                { Value : "Christmas Island", Text : "Christmas Island" },
                { Value : "Cocos (Keeling) Islands", Text : "Cocos (Keeling) Islands" },
                { Value : "Colombia", Text : "Colombia" },
                { Value : "Comoros", Text : "Comoros" },
                { Value : "Congo", Text : "Congo" },
                { Value : "Congo, The Democratic Republic of The", Text : "Congo, The Democratic Republic of The" },
                { Value : "Cook Islands", Text : "Cook Islands" },
                { Value : "Costa Rica", Text : "Costa Rica" },
                { Value : "Cote D'ivoire", Text : "Cote D'ivoire" },
                { Value : "Croatia", Text : "Croatia" },
                { Value : "Cuba", Text : "Cuba" },
                { Value : "Cyprus", Text : "Cyprus" },
                { Value : "Czech Republic", Text : "Czech Republic" },
                { Value : "Denmark", Text : "Denmark" },
                { Value : "Djibouti", Text : "Djibouti" },
                { Value : "Dominica", Text : "Dominica" },
                { Value : "Dominican Republic", Text : "Dominican Republic" },
                { Value : "Ecuador", Text : "Ecuador" },
                { Value : "Egypt", Text : "Egypt" },
                { Value : "El Salvador", Text : "El Salvador" },
                { Value : "Equatorial Guinea", Text : "Equatorial Guinea" },
                { Value : "Eritrea", Text : "Eritrea" },
                { Value : "Estonia", Text : "Estonia" },
                { Value : "Ethiopia", Text : "Ethiopia" },
                { Value : "Falkland Islands (Malvinas)", Text : "Falkland Islands (Malvinas)" },
                { Value : "Faroe Islands", Text : "Faroe Islands" },
                { Value : "Fiji", Text : "Fiji" },
                { Value : "Finland", Text : "Finland" },
                { Value : "France", Text : "France" },
                { Value : "French Guiana", Text : "French Guiana" },
                { Value : "French Polynesia", Text : "French Polynesia" },
                { Value : "French Southern Territories", Text : "French Southern Territories" },
                { Value : "Gabon", Text : "Gabon" },
                { Value : "Gambia", Text : "Gambia" },
                { Value : "Georgia", Text : "Georgia" },
                { Value : "Germany", Text : "Germany" },
                { Value : "Ghana", Text : "Ghana" },
                { Value : "Gibraltar", Text : "Gibraltar" },
                { Value : "Greece", Text : "Greece" },
                { Value : "Greenland", Text : "Greenland" },
                { Value : "Grenada", Text : "Grenada" },
                { Value : "Guadeloupe", Text : "Guadeloupe" },
                { Value : "Guam", Text : "Guam" },
                { Value : "Guatemala", Text : "Guatemala" },
                { Value : "Guinea", Text : "Guinea" },
                { Value : "Guinea-bissau", Text : "Guinea-bissau" },
                { Value : "Guyana", Text : "Guyana" },
                { Value : "Haiti", Text : "Haiti" },
                { Value : "Heard Island and Mcdonald Islands", Text : "Heard Island and Mcdonald Islands" },
                { Value : "Holy See (Vatican City State)", Text : "Holy See (Vatican City State)" },
                { Value : "Honduras", Text : "Honduras" },
                { Value : "Hong Kong", Text : "Hong Kong" },
                { Value : "Hungary", Text : "Hungary" },
                { Value : "Iceland", Text : "Iceland" },
                { Value : "India", Text : "India" },
                { Value : "Indonesia", Text : "Indonesia" },
                { Value : "Iran, Islamic Republic of", Text : "Iran, Islamic Republic of" },
                { Value : "Iraq", Text : "Iraq" },
                { Value : "Ireland", Text : "Ireland" },
                { Value : "Israel", Text : "Israel" },
                { Value : "Italy", Text : "Italy" },
                { Value : "Jamaica", Text : "Jamaica" },
                { Value : "Japan", Text : "Japan" },
                { Value : "Jordan", Text : "Jordan" },
                { Value : "Kazakhstan", Text : "Kazakhstan" },
                { Value : "Kenya", Text : "Kenya" },
                { Value : "Kiribati", Text : "Kiribati" },
                { Value : "Korea, Democratic People's Republic of", Text : "Korea, Democratic People's Republic of" },
                { Value : "Korea, Republic of", Text : "Korea, Republic of" },
                { Value : "Kuwait", Text : "Kuwait" },
                { Value : "Kyrgyzstan", Text : "Kyrgyzstan" },
                { Value : "Lao People's Democratic Republic", Text : "Lao People's Democratic Republic" },
                { Value : "Latvia", Text : "Latvia" },
                { Value : "Lebanon", Text : "Lebanon" },
                { Value : "Lesotho", Text : "Lesotho" },
                { Value : "Liberia", Text : "Liberia" },
                { Value : "Libyan Arab Jamahiriya", Text : "Libyan Arab Jamahiriya" },
                { Value : "Liechtenstein", Text : "Liechtenstein" },
                { Value : "Lithuania", Text : "Lithuania" },
                { Value : "Luxembourg", Text : "Luxembourg" },
                { Value : "Macao", Text : "Macao" },
                { Value : "Macedonia, The Former Yugoslav Republic of", Text : "Macedonia, The Former Yugoslav Republic of" },
                { Value : "Madagascar", Text : "Madagascar" },
                { Value : "Malawi", Text : "Malawi" },
                { Value : "Malaysia", Text : "Malaysia" },
                { Value : "Maldives", Text : "Maldives" },
                { Value : "Mali", Text : "Mali" },
                { Value : "Malta", Text : "Malta" },
                { Value : "Marshall Islands", Text : "Marshall Islands" },
                { Value : "Martinique", Text : "Martinique" },
                { Value : "Mauritania", Text : "Mauritania" },
                { Value : "Mauritius", Text : "Mauritius" },
                { Value : "Mayotte", Text : "Mayotte" },
                { Value : "Mexico", Text : "Mexico" },
                { Value : "Micronesia, Federated States of", Text : "Micronesia, Federated States of" },
                { Value : "Moldova, Republic of", Text : "Moldova, Republic of" },
                { Value : "Monaco", Text : "Monaco" },
                { Value : "Mongolia", Text : "Mongolia" },
                { Value : "Montserrat", Text : "Montserrat" },
                { Value : "Morocco", Text : "Morocco" },
                { Value : "Mozambique", Text : "Mozambique" },
                { Value : "Myanmar", Text : "Myanmar" },
                { Value : "Namibia", Text : "Namibia" },
                { Value : "Nauru", Text : "Nauru" },
                { Value : "Nepal", Text : "Nepal" },
                { Value : "Netherlands", Text : "Netherlands" },
                { Value : "Netherlands Antilles", Text : "Netherlands Antilles" },
                { Value : "New Caledonia", Text : "New Caledonia" },
                { Value : "New Zealand", Text : "New Zealand" },
                { Value : "Nicaragua", Text : "Nicaragua" },
                { Value : "Niger", Text : "Niger" },
                { Value : "Nigeria", Text : "Nigeria" },
                { Value : "Niue", Text : "Niue" },
                { Value : "Norfolk Island", Text : "Norfolk Island" },
                { Value : "Northern Mariana Islands", Text : "Northern Mariana Islands" },
                { Value : "Norway", Text : "Norway" },
                { Value : "Oman", Text : "Oman" },
                { Value : "Pakistan", Text : "Pakistan" },
                { Value : "Palau", Text : "Palau" },
                { Value : "Palestinian Territory, Occupied", Text : "Palestinian Territory, Occupied" },
                { Value : "Panama", Text : "Panama" },
                { Value : "Papua New Guinea", Text : "Papua New Guinea" },
                { Value : "Paraguay", Text : "Paraguay" },
                { Value : "Peru", Text : "Peru" },
                { Value : "Philippines", Text : "Philippines" },
                { Value : "Pitcairn", Text : "Pitcairn" },
                { Value : "Poland", Text : "Poland" },
                { Value : "Portugal", Text : "Portugal" },
                { Value : "Puerto Rico", Text : "Puerto Rico" },
                { Value : "Qatar", Text : "Qatar" },
                { Value : "Reunion", Text : "Reunion" },
                { Value : "Romania", Text : "Romania" },
                { Value : "Russian Federation", Text : "Russian Federation" },
                { Value : "Rwanda", Text : "Rwanda" },
                { Value : "Saint Helena", Text : "Saint Helena" },
                { Value : "Saint Kitts and Nevis", Text : "Saint Kitts and Nevis" },
                { Value : "Saint Lucia", Text : "Saint Lucia" },
                { Value : "Saint Pierre and Miquelon", Text : "Saint Pierre and Miquelon" },
                { Value : "Saint Vincent and The Grenadines", Text : "Saint Vincent and The Grenadines" },
                { Value : "Samoa", Text : "Samoa" },
                { Value : "San Marino", Text : "San Marino" },
                { Value : "Sao Tome and Principe", Text : "Sao Tome and Principe" },
                { Value : "Saudi Arabia", Text : "Saudi Arabia" },
                { Value : "Senegal", Text : "Senegal" },
                { Value : "Serbia and Montenegro", Text : "Serbia and Montenegro" },
                { Value : "Seychelles", Text : "Seychelles" },
                { Value : "Sierra Leone", Text : "Sierra Leone" },
                { Value : "Singapore", Text : "Singapore" },
                { Value : "Slovakia", Text : "Slovakia" },
                { Value : "Slovenia", Text : "Slovenia" },
                { Value : "Solomon Islands", Text : "Solomon Islands" },
                { Value : "Somalia", Text : "Somalia" },
                { Value : "South Africa", Text : "South Africa" },
                { Value : "South Georgia and The South Sandwich Islands", Text : "South Georgia and The South Sandwich Islands" },
                { Value : "Spain", Text : "Spain" },
                { Value : "Sri Lanka", Text : "Sri Lanka" },
                { Value : "Sudan", Text : "Sudan" },
                { Value : "Suriname", Text : "Suriname" },
                { Value : "Svalbard and Jan Mayen", Text : "Svalbard and Jan Mayen" },
                { Value : "Swaziland", Text : "Swaziland" },
                { Value : "Sweden", Text : "Sweden" },
                { Value : "Switzerland", Text : "Switzerland" },
                { Value : "Syrian Arab Republic", Text : "Syrian Arab Republic" },
                { Value : "Taiwan, Province of China", Text : "Taiwan, Province of China" },
                { Value : "Tajikistan", Text : "Tajikistan" },
                { Value : "Tanzania, United Republic of", Text : "Tanzania, United Republic of" },
                { Value : "Thailand", Text : "Thailand" },
                { Value : "Timor-leste", Text : "Timor-leste" },
                { Value : "Togo", Text : "Togo" },
                { Value : "Tokelau", Text : "Tokelau" },
                { Value : "Tonga", Text : "Tonga" },
                { Value : "Trinidad and Tobago", Text : "Trinidad and Tobago" },
                { Value : "Tunisia", Text : "Tunisia" },
                { Value : "Turkey", Text : "Turkey" },
                { Value : "Turkmenistan", Text : "Turkmenistan" },
                { Value : "Turks and Caicos Islands", Text : "Turks and Caicos Islands" },
                { Value : "Tuvalu", Text : "Tuvalu" },
                { Value : "Uganda", Text : "Uganda" },
                { Value : "Ukraine", Text : "Ukraine" },
                { Value : "United Arab Emirates", Text : "United Arab Emirates" },
                { Value : "United Kingdom", Text : "United Kingdom" },
                { Value : "United States Minor Outlying Islands", Text : "United States Minor Outlying Islands" },
                { Value : "Uruguay", Text : "Uruguay" },
                { Value : "Uzbekistan", Text : "Uzbekistan" },
                { Value : "Vanuatu", Text : "Vanuatu" },
                { Value : "Venezuela", Text : "Venezuela" },
                { Value : "Viet Nam", Text : "Viet Nam" },
                { Value : "Virgin Islands, British", Text : "Virgin Islands, British" },
                { Value : "Virgin Islands, U.S.", Text : "Virgin Islands, U.S." },
                { Value : "Wallis and Futuna", Text : "Wallis and Futuna" },
                { Value : "Western Sahara", Text : "Western Sahara" },
                { Value : "Yemen", Text : "Yemen" },
                { Value : "Zambia", Text : "Zambia" },
                { Value : "Zimbabwe", Text : "Zimbabwe" },
            ]
        }
    }
}
